services:
  nginx:
    build:
      context: ./infra/nginx
  
    container_name: rc-backend
    ports:
      - "80:80"
    volumes:
      - ./web-review-center:/srv/app # replace project_name with your desired value
    depends_on:
      - php

  php:
    build:
      context: ./infra/php
    container_name: rc-php
    expose:
      - "9000" # replaced 9001 if there is conflict on this port.
    ports:
      - "8081:9000" # replaced 9001 if there is conflict on this port.
    volumes:
      - ./web-review-center:/srv/app # replace project_name with your desired value
    depends_on:
      - mysql

  mysql:
    build:
      context: ./infra/mysql
    container_name: rc-db
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      - "LANG=C.UTF-8"
      - "MYSQL_ROOT_PASSWORD=root" # replaced password on your desired value
      - "MYSQL_DATABASE=wrc_database" # replacead database name on your desired value
      - "MYSQL_PASSWORD=WRC2025"
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql

networks:
  default:
    driver: bridge

volumes:
  mysql-volume:
    driver: local
